repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-toml
      - id: check-json

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: mypy
        name: mypy
        entry: mypy --strict aliceio
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
