version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --only docs
    - poetry env info
    - cat mkdocs.yml
    - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
  configuration: mkdocs.yml
