site_name: AliceIO Docs
site_author: AliceIO
site_description: Awesome Alice framework
site_url: https://aliceio.rtfd.io/
repo_name: aliceio
repo_url: https://github.com/K1rL3s/aliceio
edit_uri: edit/master/docs/
copyright: <a href="https://github.com/K1rL3s/aliceio/tree/master/LICENSE" target="_blank" rel="noopener">View maintainers</a>

extra:
  generator: false
  disqus: ""
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/aliceio_ru
      name: Наш ТГ чат

nav:
  - Документация:
      - index.md
      - Пользовательский уровень:
          - Handling:
              - Handlers:
                  - Base: aliceio/handlers/base.md
                  - AudioPlayer: aliceio/handlers/audio_player.md
                  - ButtonPressed: aliceio/handlers/button_pressed.md
                  - Message: aliceio/handlers/message.md
                  - Purchase: aliceio/handlers/purchase.md
                  - ShowPull: aliceio/handlers/show_pull.md
                  - Error: aliceio/handlers/error.md
                  - Timeout: aliceio/handlers/timeout.md
              - Dispatcher:
                  - Dispatcher: aliceio/dispatcher/dispatcher.md
                  - Flags: aliceio/dispatcher/flags.md
                  - Router: aliceio/dispatcher/router.md
                  - Middlewares:
                      - Base: aliceio/dispatcher/middlewares/base.md
              - Webhook:
                  - AiohttpServer: aliceio/webhook/aiohttp_server.md

          - Tools:
              - Filters:
                  - Base: aliceio/filters/base.md
                  - State: aliceio/filters/state.md
                  - Exception: aliceio/filters/exception.md
                  - Logic: aliceio/filters/logic.md
                  - MagicData: aliceio/filters/magic_data.md
              - FSM:
                  - Context: aliceio/fsm/context.md
                  - State: aliceio/fsm/state.md
                  - Strategy: aliceio/fsm/strategy.md
                  - Storages:
                      - Base: aliceio/fsm/storage/base.md
                      - MemoryStorage: aliceio/fsm/storage/memory.md
                      - ApiStorage: aliceio/fsm/storage/api.md
              - Methods:
                  - Base: aliceio/methods/base.md
                  - Status: aliceio/methods/status.md
                  - Images:
                      - Upload: aliceio/methods/images/upload_image.md
                      - Get: aliceio/methods/images/get_images.md
                      - Delete: aliceio/methods/images/delete_image.md
                  - Sounds:
                      - Upload: aliceio/methods/sounds/upload_sound.md
                      - Get: aliceio/methods/sounds/get_sounds.md
                      - Delete: aliceio/methods/sounds/delete_sound.md
              - Types:
                  - AliceEvent: aliceio/types/alice_event.md
                  - AliceRequest: aliceio/types/alice_request.md
                  - AliceResponse: aliceio/types/alice_response.md
                  - AnalyticEvent: aliceio/types/analytic_event.md
                  - Analytics: aliceio/types/analytics.md
                  - ApiState: aliceio/types/api_state.md
                  - Application: aliceio/types/application.md
                  - AudioPlayer: aliceio/types/audio_player.md
                  - AudioPlayerDirective: aliceio/types/audio_player_directive.md
                  - AudioPlayerError: aliceio/types/audio_player_error.md
                  - AudioPlayerItem: aliceio/types/audio_player_item.md
                  - Base: aliceio/types/base.md
                  - BigImage: aliceio/types/big_image.md
                  - ButtonPressed: aliceio/types/button_pressed.md
                  - Card: aliceio/types/card.md
                  - CardFooter: aliceio/types/card_footer.md
                  - CardHeader: aliceio/types/card_header.md
                  - Datetime: aliceio/types/datetime.md
                  - Directives: aliceio/types/directives.md
                  - Entity: aliceio/types/entity.md
                  - ErrorEvent: aliceio/types/error_event.md
                  - ErrorResult: aliceio/types/error_result.md
                  - FIOEntity: aliceio/types/fio_entity.md
                  - GEOEntity: aliceio/types/geo_entity.md
                  - ImageGallery: aliceio/types/image_gallery.md
                  - ImageGalleryItem: aliceio/types/image_gallery_item.md
                  - InputFile: aliceio/types/input_file.md
                  - Interface: aliceio/types/interfaces.md
                  - ItemImage: aliceio/types/item_image.md
                  - ItemsList: aliceio/types/items_list.md
                  - Markup: aliceio/types/markup.md
                  - MediaButton: aliceio/types/media_button.md
                  - Message: aliceio/types/message.md
                  - Meta: aliceio/types/meta.md
                  - MetaData: aliceio/types/metadata.md
                  - NLU: aliceio/types/nlu.md
                  - NLUEntity: aliceio/types/nlu_entity.md
                  - NumberEntity: aliceio/types/number_entity.md
                  - Payload: aliceio/types/payload.md
                  - Purchase: aliceio/types/purchase.md
                  - Quota: aliceio/types/quota.md
                  - Response: aliceio/types/response.md
                  - Result: aliceio/types/result.md
                  - Session: aliceio/types/session.md
                  - ShowItemMeta: aliceio/types/show_item_meta.md
                  - ShowPull: aliceio/types/show_pull.md
                  - SpaceStatus: aliceio/types/space_status.md
                  - Stream: aliceio/types/stream.md
                  - TextButton: aliceio/types/text_button.md
                  - TimeOutEvent: aliceio/types/timeout_event.md
                  - TokensEntity: aliceio/types/tokens_entity.md
                  - Update: aliceio/types/update.md
                  - UploadedImage: aliceio/types/uploaded_image.md
                  - UploadedSound: aliceio/types/uploaded_sound.md
                  - URL: aliceio/types/url.md
                  - User: aliceio/types/user.md
              - Utils:
                  - MagicFilter: aliceio/utils/magic_filter.md
          - Client:
              - Skill: aliceio/client/skill.md

      - Продвинутый уровень:
          - Handling:
              - Webhook:
                  - Security: aliceio/webhook/security.md
          - Tools:
              - Enums:
                  - aliceio/enums/all_enums.md
              - FSM:
                  - Redis:
                      - RedisStorage: aliceio/fsm/storage/redis/redis.md
                      - DefaultKeyBuilder: aliceio/fsm/storage/redis/default_key_builder.md
                      - KeyBuilder: aliceio/fsm/storage/redis/key_builder.md
              - Utils:
                  - Builders:
                      - Example: aliceio/utils/builders.md
                      - Base: aliceio/utils/builders/builder.md
                      - ImageGalleryBuilder: aliceio/utils/builders/image_gallery_builder.md
                      - ItemsListBuilder: aliceio/utils/builders/items_list_builder.md
                      - TextButtonBuilder: aliceio/utils/builders/text_button_builder.md
          - Client:
              - Alice: aliceio/client/alice.md
              - ContextController: aliceio/client/context_controller.md
              - Session:
                  - Base: aliceio/client/session/base.md
                  - Aiohttp: aliceio/client/session/aiohttp.md
                  - Middlewares:
                      - Base: aliceio/client/session/middlewares/base.md
                      - Manager: aliceio/client/session/middlewares/manager.md
                      - RequestLogging: aliceio/client/session/middlewares/request_logging.md

      - Внутреннее устройство:
          - Handling:
              - Dispatcher:
                  - Observers:
                      - Base: aliceio/dispatcher/event/bases.md
                      - EventObserver: aliceio/dispatcher/event/event.md
                      - AliceEventObserver: aliceio/dispatcher/event/alice.md
                      - Handlers: aliceio/dispatcher/event/handler.md
                  - Middlewares:
                      - Manager: aliceio/dispatcher/middlewares/manager.md
                      - UserContext: aliceio/dispatcher/middlewares/user_context.md
                      - Error: aliceio/dispatcher/middlewares/error.md
                      - ResponseConvert: aliceio/dispatcher/middlewares/response_convert.md
          - Tools:
              - FSM:
                  - Middlewares:
                      - FSMContextMiddleware: aliceio/fsm/middlewares/fsm_context.md
                      - FSMApiStorageMiddleware: aliceio/fsm/middlewares/api_storage.md
              - Utils:
                  - Funcs: aliceio/utils/funcs.md
                  - Mixins: aliceio/utils/mixins.md
                  - Warnings: aliceio/utils/warnings.md

  - Туториал:
      - tutorial/tutorial.md
      - Первый навык: tutorial/first-skill.md
      - Разделение кода: tutorial/code-separation.md
      - Методы API: tutorial/methods.md
      - Фильтры: tutorial/filters.md
      - Мидлвари: tutorial/middlewares.md
      - Машина состояний: tutorial/finite-state-machine.md
      - Кнопки и альбомы: tutorial/builders.md
      - Обработка ошибок: tutorial/error-handling.md
      - Обработка таймаута: tutorial/timeout-handling.md
      - FAQ: tutorial/faq.md


theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto Mono
    code: Monaco
  logo: _static/logo_aliceio_trans.png
  favicon: _static/logo_aliceio_trans.png


markdown_extensions:
  - admonition:
  - md_in_html:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify  # noqa
        kwds:
          case: lower
      permalink: ""
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      normalize_issue_symbols: true
      user: K1rL3s
      repo: aliceio
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      guess_lang: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:


plugins:
  - search:
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: true
            docstring_section_style: list
            docstring_style: sphinx
            group_by_category: true
            show_docstring_description: true
            merge_init_into_class: false
            show_root_heading: true
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true


extra_css:
  - _css/style.css
