site_name: AliceIO Docs
site_author: AliceIO
site_description: Awesome Alice framework
site_url: https://aliceio.rtfd.io/ru/latest/
repo_name: aliceio
repo_url: https://github.com/K1rL3s/aliceio
edit_uri: edit/master/docs/
copyright: <a href="https://github.com/K1rL3s/aliceio/tree/master/LICENSE" target="_blank" rel="noopener">Лицензия</a>

extra:
  generator: false
  disqus: ""
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/aliceio_ru
      name: Наш ТГ чат

nav:
  - Документация:
      - index.md
      - Установка: install.md
      - API Алисы:
          - Навык: aliceio/client/skill.md
          - Enums: aliceio/enums/all-enums.md
          - Методы:
              - Base: aliceio/methods/base.md
              - Статус: aliceio/methods/status.md
              - Изображения:
                  - Загрузить: aliceio/methods/images/upload-image.md
                  - Получить: aliceio/methods/images/get-images.md
                  - Удалить: aliceio/methods/images/delete-image.md
              - Звуки:
                  - Загрузить: aliceio/methods/sounds/upload-sound.md
                  - Получить: aliceio/methods/sounds/get-sounds.md
                  - Удалить: aliceio/methods/sounds/delete-sound.md
          - Типы:
              - AliceEvent: aliceio/types/alice-event.md
              - AliceRequest: aliceio/types/alice-request.md
              - AliceResponse: aliceio/types/alice-response.md
              - AnalyticEvent: aliceio/types/analytic-event.md
              - Analytics: aliceio/types/analytics.md
              - ApiState: aliceio/types/api-state.md
              - Application: aliceio/types/application.md
              - AudioPlayer: aliceio/types/audio-player.md
              - AudioPlayerDirective: aliceio/types/audio-player-directive.md
              - AudioPlayerError: aliceio/types/audio-player-error.md
              - AudioPlayerItem: aliceio/types/audio-player-item.md
              - Base: aliceio/types/base.md
              - BigImage: aliceio/types/big-image.md
              - ButtonPressed: aliceio/types/button-pressed.md
              - Card: aliceio/types/card.md
              - CardFooter: aliceio/types/card-footer.md
              - CardHeader: aliceio/types/card-header.md
              - Datetime: aliceio/types/datetime.md
              - Directives: aliceio/types/directives.md
              - Entity: aliceio/types/entity.md
              - ErrorEvent: aliceio/types/error-event.md
              - ErrorResult: aliceio/types/error-result.md
              - FIOEntity: aliceio/types/fio-entity.md
              - GEOEntity: aliceio/types/geo-entity.md
              - ImageGallery: aliceio/types/image-gallery.md
              - ImageGalleryItem: aliceio/types/image-gallery-item.md
              - InputFile: aliceio/types/input-file.md
              - Interface: aliceio/types/interfaces.md
              - ItemImage: aliceio/types/item-image.md
              - ItemsList: aliceio/types/items-list.md
              - Markup: aliceio/types/markup.md
              - MediaButton: aliceio/types/media-button.md
              - Message: aliceio/types/message.md
              - Meta: aliceio/types/meta.md
              - MetaData: aliceio/types/metadata.md
              - NLU: aliceio/types/nlu.md
              - NLUEntity: aliceio/types/nlu-entity.md
              - NumberEntity: aliceio/types/number-entity.md
              - Payload: aliceio/types/payload.md
              - Purchase: aliceio/types/purchase.md
              - Quota: aliceio/types/quota.md
              - Response: aliceio/types/response.md
              - Result: aliceio/types/result.md
              - Session: aliceio/types/session.md
              - ShowItemMeta: aliceio/types/show-item-meta.md
              - ShowPull: aliceio/types/show-pull.md
              - SpaceStatus: aliceio/types/space-status.md
              - Stream: aliceio/types/stream.md
              - TextButton: aliceio/types/text-button.md
              - TimeoutEvent: aliceio/types/timeout-event.md
              - TokensEntity: aliceio/types/tokens-entity.md
              - Update: aliceio/types/update.md
              - UploadedImage: aliceio/types/uploaded-image.md
              - UploadedSound: aliceio/types/uploaded-sound.md
              - URL: aliceio/types/url.md
              - User: aliceio/types/user.md
          - Клиент:
              - Сервер Алисы: aliceio/client/alice.md
              - ContextController: aliceio/client/context-controller.md
              - Сессия:
                  - Base: aliceio/client/session/base.md
                  - Aiohttp: aliceio/client/session/aiohttp.md
                  - Мидлвари:
                      - Base: aliceio/client/session/middlewares/base.md
                      - Manager: aliceio/client/session/middlewares/manager.md
                      - RequestLogging: aliceio/client/session/middlewares/request-logging.md

      - Обработка событий:
          - Роутер: aliceio/dispatcher/router.md
          - Диспетчер: aliceio/dispatcher/dispatcher.md
          - Фильтрация:
              - Base: aliceio/filters/base.md
              - Состояния: aliceio/filters/state.md
              - Исключение: aliceio/filters/exception.md
              - Комбинации: aliceio/filters/logic.md
              - MagicData: aliceio/filters/magic-data.md
              - MagicFilter: aliceio/filters/magic-filter.md
          - Вебхук:
              - Aiohttp: aliceio/webhook/aiohttp-server.md
              - Security: aliceio/webhook/security.md
          - Машина состояний:
              - Контекст: aliceio/fsm/context.md
              - Состояние: aliceio/fsm/state.md
              - Стратегия: aliceio/fsm/strategy.md
              - Хранилища:
                  - Base: aliceio/fsm/storage/base.md
                  - MemoryStorage: aliceio/fsm/storage/memory.md
                  - ApiStorage: aliceio/fsm/storage/api.md
                  - Redis:
                      - RedisStorage: aliceio/fsm/storage/redis/redis.md
                      - DefaultKeyBuilder: aliceio/fsm/storage/redis/default-key-builder.md
                      - KeyBuilder: aliceio/fsm/storage/redis/key-builder.md
          - Мидлвари:
              - Base: aliceio/dispatcher/middlewares/base.md
          - Флаги: aliceio/dispatcher/flags.md
          - Class-based хэндлеры:
              - Base: aliceio/handlers/base.md
              - AudioPlayer: aliceio/handlers/audio-player.md
              - ButtonPressed: aliceio/handlers/button-pressed.md
              - Message: aliceio/handlers/message.md
              - Purchase: aliceio/handlers/purchase.md
              - ShowPull: aliceio/handlers/show-pull.md
              - Error: aliceio/handlers/error.md
              - Timeout: aliceio/handlers/timeout.md

      - Утилсы:
          - Билдеры:
              - Описание: aliceio/utils/builders.md
              - Base: aliceio/utils/builders/builder.md
              - ImageGalleryBuilder: aliceio/utils/builders/image-gallery-builder.md
              - ItemsListBuilder: aliceio/utils/builders/items-list-builder.md
              - TextButtonBuilder: aliceio/utils/builders/text-button-builder.md

      - Внутреннее устройство:
          - Наблюдатели:
              - Base: aliceio/dispatcher/event/bases.md
              - EventObserver: aliceio/dispatcher/event/event.md
              - AliceEventObserver: aliceio/dispatcher/event/alice.md
              - Handlers: aliceio/dispatcher/event/handler.md
          - Мидлвари:
              - Manager: aliceio/dispatcher/middlewares/manager.md
              - UserContext: aliceio/dispatcher/middlewares/user-context.md
              - Error: aliceio/dispatcher/middlewares/error.md
              - ResponseConvert: aliceio/dispatcher/middlewares/response-convert.md
              - FSMContextMiddleware: aliceio/fsm/middlewares/fsm-context.md
              - FSMApiStorageMiddleware: aliceio/fsm/middlewares/api-storage.md
          - Утилсы:
              - Funcs: aliceio/utils/funcs.md
              - Mixins: aliceio/utils/mixins.md
              - Warnings: aliceio/utils/warnings.md

  - Туториал:
      - tutorial/index.md
      - Начало: tutorial/start.md
      - Первый навык: tutorial/first-skill.md
      - Методы API: tutorial/methods.md
      - Фильтры: tutorial/filters.md
      - Мидлвари: tutorial/middlewares.md
      - Машина состояний: tutorial/finite-state-machine.md
      - Кнопки и альбомы: tutorial/builders.md
      - Обработка ошибок: tutorial/error-handling.md
      - Особые события: tutorial/special-events.md
      - Внедрение зависимостей: tutorial/dependency-injection.md
      - Полноценный навык: tutorial/full-skill.md
      - FAQ: tutorial/faq.md


theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto Mono
    code: Monaco
  logo: _static/logo-aliceio-trans.png
  favicon: _static/logo-aliceio-trans.png


markdown_extensions:
  - admonition:
  - md_in_html:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      normalize_issue_symbols: true
      user: K1rL3s
      repo: aliceio
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      guess_lang: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:


plugins:
  - search:
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: true
            docstring_section_style: list
            docstring_style: sphinx
            group_by_category: true
            show_docstring_description: true
            merge_init_into_class: false
            show_root_heading: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true


extra_css:
  - _css/style.css
