name: "PyPI Release"

on:
  release:
    types:
      - published
    tags:
      - 'v0.*'

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Resolve version
        id: package-version
        run: echo "value=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')" >> $GITHUB_OUTPUT

      - name: Build source distribution
        run: python -m build .

      - name: Try install wheel
        run: |
          pip install -U virtualenv
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/aliceio-*.whl
          venv/bin/python -c "import aliceio; print(aliceio.__version__)"
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/aliceio/${{ steps.package-version.outputs.value }}/
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
